# $OpenBSD: Makefile,v 1.20 2014/07/12 19:39:49 giovanni Exp $

SHARED_ONLY =	Yes

COMMENT =	Object(ish) Interface to utmp files.

MODULES =	cpan
DISTNAME =	Sys-Utmp-1.7
EPOCH =		1
CATEGORIES =	sysutils local

# Perl
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB += c

#RUN_DEPENDS=	converters/p5-Types-Serialiser \
#		devel/p5-common-sense

.include <bsd.port.mk>
